name: Build Rust Server Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: rustserver
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: rustserver-release-binary-${{ matrix.os }}
          path: |
            rustserver/target/release/rustserver*
            rustserver/target/release/rustserver.exe
